### PR TITLE
upgrade to remix v1.17.0 and native ESM

### PR DESCRIPTION
**Pull request by onemen**
@kentcdodds 

just need to wait for `workshop-app` next version after https://github.com/epicweb-dev/kcdshop/pull/67 will merge 

i've tested the app and all the test locally, and everything looking good.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thanks!

**Comment by onemen** [comment]
@kentcdodds 

this PR is ready

I can split the first big commit to smaller commits if it will help.

I am planing to use the same approach to the other workshops repositories.

**Comment by onemen** [comment]
do we need `package-lock.json` for each `exercise` ?

**Comment by kentcdodds** [comment]
Maybe we should get kcdshop upgraded to Remix v1.17.0 with the v2_headers config option set? Then we can upgrade the workshop to that version.

As for package-lock.json, I don't think we want that because this is being managed via workspaces with npm, so there should just be one `package-lock.json` in the root.

**Comment by onemen** [comment]
> Maybe we should get kcdshop upgraded to Remix v1.17.0 with the v2_headers config option set?

OK, i will push a PR later.

once new kcdshop  version is out i will push update to here

**Comment by kentcdodds** [comment]
Awesome. I'll keep an eye on this PR and once it's updated with the latest kcdshop and remix then I'll merge. Thank you so much for putting so much time and effort into this 🙏

**Comment by onemen** [comment]
I am waiting to `kcdshop` version that includes [#70](https://github.com/epicweb-dev/kcdshop/pull/70)

**Comment by onemen** [comment]
It ready

**Comment by kentcdodds** [comment]
Thanks a lot!

**Pull request merged**
